### ISSUE TITLE
Unexpected rotation on image_s3_i0 & Discontinuous contrast flow on image_s48_i0/i1/i2 in DIAS dataset

### ISSUE THREAD

**Issue by silver-18** [lseventeen/DIAS#4]
Thanks for your efforts in making this dataset publicly available!

Upon downloading and reviewing the data, we have identified some potential issues as follows:

- There is an unexpected rotation on image_s3_i0, which inconsists with other images in image_s3.

- There is a discontinuous contrast flow on image_s48_i0/i1/i2. It seems that i1 is the latter frame of i2.

- All the .png images in the unlabeled_DSA folder are unable to be opened by the default image viewer on Ubuntu 20.04, with the error message stating 'Not a PNG file'. But they can be open on Windows or in other softwares like Mevislab. I wonder if it is because of the non-standard .png file format.

It is suggested that you recheck all the image files in the public dataset to prevent the issue mentioned above. Thank you very much for your patience and attention. I look forward to yourcorrection of this issue and the subsequent release of the revised data. :smiley:

**Comment by lseventeen** [comment]
Thank you for bringing these issues to our attention!

I have addressed the concerns as follows:

- Rotation Issue in image_s3_i0: This image has been corrected to ensure consistent orientation with the other images in the image_s3 set.

- Discontinuous Contrast Flow in image_s48_i0/i1/i2: The frames have been reviewed and corrected. The sequence is now in the proper order.

- Non-standard PNG Files in unlabeled_DSA Folder: The issue was identified as being caused by the renaming process of the images. The files have been reprocessed and new versions generated. The updated images should now be compatible with the default image viewer on Ubuntu 20.04.

The revised dataset has been uploaded. Please download the latest version and let us know if you encounter any further issues.

Thank you for your patience and for helping us improve the dataset.

**Comment by silver-18** [comment]
Thank you for your detailed reply and for the corrections made to the dataset!

I have downloaded the latest version of the dataset, and I believe the issues I raised have been resolved. :smiley:
